CFG_MT_DEBUG=y
CFG_MT_OPTM_SIZE_SUPPORT=n
CFG_MT_STATIC_LINK=n

CFG_MT_WDG_SUPPORT=y
CFG_MT_MTEST=y

CFG_MT_PROC_SUPPORT=y
CFG_MT_PLAYER_SUPPORT=y
CFG_MT_WIFI_SUPPORT=y
CFG_MT_WIFI_DEVICE_MT7601U=y
CFG_MT_WIFI_DEVICE_RTL8188EUS=y
CFG_MT_WIFI_MODE_STA=y
CFG_MT_WIFI_MODE_AP=n
CFG_MT_KERNEL_VERSION=linux-3.18.0
CFG_MT_DOLBY_SUPPORT=n

#choose mt suplyer type
##the old fileplayer
CFG_MT_SUPLAYER_SUPPORT=y
#gst player
CFG_MT_GST_SUPLAYER_SUPPORT=y
CFG_ENABLE_GST_DASH_DEMUX=n

#pvr
CFG_MT_PVR_SUPPORT=y
CFG_MT_PVR_COMMON_SUPPORT=y

CFG_MT_FRONTEND_SUPPORT=y
CFG_MT_DISEQC_SUPPORT=y

#
# Trace Video Image Flow
#
CFG_DEBUG_V_IMG_FLOW=n

#
# Dump Video ES/Descriptor Buffer Stat
#
CFG_DEBUG_V_BUF_STAT=n

#
# Dump Video ES Data to "/media/sda1/dump_v.es"
# Support File Play only, not support DVB.
#
CFG_DUMP_V_ES_BUF=n


CFG_MT_ZLIB_SUPPORT=y
